### ISSUE TITLE
App crashing with 60fps or audio on

### ISSUE THREAD

**Issue by sksb2180** [MarcAnt01/Fluent-Screen-Recorder#110]
The app is crashing either with 60 fps and audio recording on or both. It works fine with 30 fps with any bitrate and microphone recording. 

win ver: 22000.493

**Comment by sksb2180** [comment]
It crashes even with 30 fps and audio recording on, I'm unable to record my classes :(

**Comment by MarcAnt01** [comment]
Thanks for your report, I am so sorry about your issue, mic recording is causing so many crashes and in spite of all my attempts, none of the fixes seems to be working 100%. If you want I can provide you with a test version that seems to be working, but I highly discourage you to use it for long recordings, since the app hasn't been optimized for that usage

**Comment by MarcAnt01** [comment]
Hello, sorry, but I forgot to send you the test version. Anyway, I've fixed some crashes recently and I would happy to reach out to you somehow, do you have any contact information Telegram/Discord/Twitter where we can talk?

**Comment by sksb2180** [comment]
Hi friend, I'm sorry but closing this issue as i got used to of using obs to record stuff. Thanks a lot for your work 😃

**Comment by MarcAnt01** [comment]
@sksb2180 understood, if you're still interested, there's a beta version being tested that fixes most of the crashes

**Comment by sksb2180** [comment]
Thanks a lot 😊, I appreciate your support.

**Comment by MarcAnt01** [comment]
You're welcome, if you want to try the beta version. Tell me a way to reach out to you (e.g. mail/Telegram) and I'll add you to the beta version, since it's not open to everyone for the moment, but I got reports of most of the crashes fixed
