### ISSUE TITLE
Resolution should match source size

### ISSUE THREAD

**Issue by Gavin-Williams** [MarcAnt01/Fluent-Screen-Recorder#30]
Resolution shows as 1920x1080. I have use source size as video resolution = on. The resolution should show 2560x1440, even when grayed out, as that's the resolution.

**Comment by MarcAnt01** [comment]
The issue here is that source size can also be different from the available options, for example my Surface Book 2 screen is 3000x2000. So that would require a major rework. Is it really important for you to see the actual value of source size in the combobox? I think that greying it makes it obvious that options there aren't selectable and also remembers the last option you've used.
