### ISSUE TITLE
Changing most of the settings will crash the application

### ISSUE THREAD

**Issue by Ahmetozefe** [MarcAnt01/Fluent-Screen-Recorder#95]
Windows 11 Pro 21H2
OS build	22000.348
App info: Latest version from Microsoft Store as of 27 November 2021

Issues:
Use source size as video resolution [disabled]
Audio Recording [enabled]
Video Preview [disabled]
Gallery View [disabled]

will all crash the app. Also the app doesn't remember the settings. After a recording is done, all settings will go back to defaults.

**Comment by MarcAnt01** [comment]
Hello, thanks for reporting:
- internal audio recording will crash the app on some devices due to the library I use for recording internal audio, this is known, but it's also hard to fix. I have already reported this in https://github.com/MarcAnt01/Fluent-Screen-Recorder/issues/92
- Settings not being saved issue is known, too https://github.com/MarcAnt01/Fluent-Screen-Recorder/issues/93 . At the moment, the best thing to do after a recording is close and reopen the app if you want to see your cached settings
