### ISSUE TITLE
better file sizes

### ISSUE THREAD

**Issue by LuanVSO** [MarcAnt01/Fluent-Screen-Recorder#96]
I like to use it to record bug repros to post on GitHub, but very frequently the video size is bigger than GitHub's maximum video size (100mb) which i them have to run through some other app (like VLC) to reencode the video to get a sensible file size.

**Comment by MarcAnt01** [comment]
Hello, I plan to add HEVC support for the future, but it requires some codecs that aren't available on all devices, so it'll be an option and even with it the improvements aren't that huge.
Anyway, the big file size is due to a high resolution/bitrate. If you want smaller files, my suggestion is to lower the resolution (disabling the option of use source size that automatically picks the highest one supported by the hardware) and the bitrate
